[package]
name = "caching_proxy_sever"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["macros", "full"] }
reqwest = { version = "0.12.9", features = ["json", "blocking"] }
httpmock = "0.7"
