[package]
name = "tui_caching_proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
caching_proxy_sever = { version = "0.1.0", path = "../caching_proxy_sever" }
serde_json = "1.0.132"
itertools = "0.13.0"
tokio = { version = "1.41.0", features = ["full"] }
